
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package miniide;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 30;
  public static final int Entero = 2;
  public static final int Mientras_SC = 43;
  public static final int Coma = 39;
  public static final int ParAbierto = 37;
  public static final int NamEntero = 4;
  public static final int Diferente = 29;
  public static final int Clase = 16;
  public static final int Menos = 19;
  public static final int Mas = 18;
  public static final int Desde_SC = 45;
  public static final int Menor = 25;
  public static final int Asignacion = 33;
  public static final int Less1 = 23;
  public static final int Por = 20;
  public static final int Mayor = 24;
  public static final int Nuevo = 14;
  public static final int Hacer_SC = 44;
  public static final int CorAbierto = 35;
  public static final int Vacio = 8;
  public static final int EndCom = 34;
  public static final int Cadena = 49;
  public static final int Publico = 11;
  public static final int Si_NoSi_SC = 41;
  public static final int EOF = 0;
  public static final int Hasta_SC = 46;
  public static final int Not = 32;
  public static final int And = 31;
  public static final int error = 1;
  public static final int NamCadena = 6;
  public static final int Imprimir = 48;
  public static final int Si_SC = 40;
  public static final int MayorIg = 26;
  public static final int Devolver = 9;
  public static final int Div = 21;
  public static final int MenorIg = 27;
  public static final int Privado = 13;
  public static final int ParCerrado = 38;
  public static final int Identificador = 50;
  public static final int SiNo_SC = 42;
  public static final int Protegido = 12;
  public static final int Extiende = 17;
  public static final int Boolean = 10;
  public static final int Decimal = 3;
  public static final int Importar = 15;
  public static final int Add1 = 22;
  public static final int NamBoolean = 7;
  public static final int NamDecimal = 5;
  public static final int Incremento_SC = 47;
  public static final int Igual = 28;
  public static final int CorCerrado = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Entero",
  "Decimal",
  "NamEntero",
  "NamDecimal",
  "NamCadena",
  "NamBoolean",
  "Vacio",
  "Devolver",
  "Boolean",
  "Publico",
  "Protegido",
  "Privado",
  "Nuevo",
  "Importar",
  "Clase",
  "Extiende",
  "Mas",
  "Menos",
  "Por",
  "Div",
  "Add1",
  "Less1",
  "Mayor",
  "Menor",
  "MayorIg",
  "MenorIg",
  "Igual",
  "Diferente",
  "Or",
  "And",
  "Not",
  "Asignacion",
  "EndCom",
  "CorAbierto",
  "CorCerrado",
  "ParAbierto",
  "ParCerrado",
  "Coma",
  "Si_SC",
  "Si_NoSi_SC",
  "SiNo_SC",
  "Mientras_SC",
  "Hacer_SC",
  "Desde_SC",
  "Hasta_SC",
  "Incremento_SC",
  "Imprimir",
  "Cadena",
  "Identificador"
  };
}

