
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package miniide.frontEnd;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int nameArch = 17;
  public static final int creacionCl = 7;
  public static final int creacionOp = 6;
  public static final int proyectoOp = 2;
  public static final int paqueteOp = 12;
  public static final int proyectoCl = 3;
  public static final int paqueteCl = 13;
  public static final int nombreCl = 5;
  public static final int nombreOp = 4;
  public static final int EOF = 0;
  public static final int CreateDate = 16;
  public static final int rutaCl = 9;
  public static final int rutaOp = 8;
  public static final int fileRote = 18;
  public static final int archivoCl = 11;
  public static final int archivoOp = 10;
  public static final int error = 1;
  public static final int lsArchCl = 15;
  public static final int lsArchOp = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "proyectoOp",
  "proyectoCl",
  "nombreOp",
  "nombreCl",
  "creacionOp",
  "creacionCl",
  "rutaOp",
  "rutaCl",
  "archivoOp",
  "archivoCl",
  "paqueteOp",
  "paqueteCl",
  "lsArchOp",
  "lsArchCl",
  "CreateDate",
  "nameArch",
  "fileRote"
  };
}

